# Generated by Django 4.2.2 on 2023-07-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='extendeduser',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='sub',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
