# Generated by Django 4.2.2 on 2023-06-29 08:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_order', models.DateTimeField()),
                ('delivery_address', models.CharField(max_length=256)),
                ('items_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_status', models.CharField(max_length=256)),
                ('payment_status', models.CharField(max_length=256)),
                ('goods_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
