# Generated by Django 4.2.2 on 2023-08-02 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_order', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=256)),
                ('items_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_status', models.CharField(max_length=256)),
                ('payment_status', models.CharField(max_length=256)),
                ('goods_ids', models.CharField(max_length=256, validators=[django.core.validators.int_list_validator])),
            ],
        ),
    ]
