# Generated by Django 4.2.2 on 2023-06-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_user_order_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods_ids',
        ),
    ]
