# Generated by Django 4.2.2 on 2023-06-29 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_goods_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=1, size=None),
            preserve_default=False,
        ),
    ]
