# Generated by Django 4.2.2 on 2023-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_goods_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods_ids',
            field=models.CharField(max_length=256),
        ),
    ]
